### ISSUE TITLE
Can't open detailed progress again after closing it with X instead of button

### ISSUE THREAD

**Issue by enumag** [07th-mod/Higurashi_Installer_WPF#10]
Using 1.15 release.

By the way the 1.15 release has 1.14 in the title bar.

**Comment by drojf** [comment]
I couldn't reproduce the issue (see this video: https://www.youtube.com/watch?v=01Ulz076on8)

Is there some step I'm not doing?

I'm on Windows 10  btw. I tried using the "windows 7" install mode but it was the same.

**Comment by enumag** [comment]
Hmm... I'll try again later and reopen with more info if I can reproduce it.
