### ISSUE TITLE
Installer not putting files in the right directory

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/Higurashi_Installer_WPF#2]
@VocalNight
Someone ran into a problem installing the console arcs using the new installer.  They sent me a [screenshot](https://i.imgur.com/Ea3LgOf.png) of their StreamingAssets folder.

Looks like it put a second StreamingAssets folder inside the first one, and it only contains the Update folder.  The other folders like CG and voice are completely missing.  No idea how this guy managed to pull this off.

**Comment by VocalNight** [comment]
Leaving a comment here too to keep a register.

Like a said on discord, ask him to get the log folder that was created in the same folder the installer is in and send to us.

Looking at the directory tree from his screenshot, the installer would validate the folder if he selected "Higurashi 04 - Himatsubushi".

So something happened during the installation process, hopefully checking the log with the install.bat for chapter 4 will help.

**Comment by VocalNight** [comment]
Not sure if he is still having the problem, but if he could use the new installer to see if the problem persists, that would be great. The new log is more detailed too.

**Comment by VocalNight** [comment]
Closing the issue for now.
