### ISSUE TITLE
Couldn't download resources for installer

### ISSUE THREAD

**Issue by nicholagon** [07th-mod/Higurashi_Installer_WPF#22]
Trying to patch Ch1 Onikakushi and got this error. I used v1.20 down to v1.17 and kept getting the same result. Running Windows 10 btw.

[PatcherLog.txt](https://github.com/07th-mod/Higurashi_Installer_WPF/files/2537740/PatcherLog.txt)

**Comment by drojf** [comment]
Are you in Japan? Sorry but we have blocked download access to Japan for copyright reasons...I should really add a message for when this happens...

A overly strong firewall could also prevent accessing the server.

As a test, try to download this file. If it fails, you have some problem connecting to our server: https://07th-mod.com/Beato/Umineko1to4.exe

**Comment by drojf** [comment]
If you come onto our discord, I can give you a workaround for now....

**Comment by nicholagon** [comment]
I'm actually in the Philippines. Hmm, and I can't seem to download that file you linked either. Actually I couldn't access 07th-mod.com at all, it just shows a 404 Not Found page.

**Comment by drojf** [comment]
no worries

If you have any other issues, feel free to open another github issue or contact us on discord.

I'll leave this open because I still need to leave a proper warning message for this error on the installer

**Comment by drojf** [comment]
New installer now gives a warning about how japan is IP blocked if you fail to download the resources file, so I think this issue can be closed (in the future we may remove the block, but it shouldn't be discussed here).
