### ISSUE TITLE
Opening debug console makes the installer unresponsive

### ISSUE THREAD

**Issue by enumag** [07th-mod/Higurashi_Installer_WPF#7]
I'm trying the 0.12 release.

When I clicked the detailed progress button, a debug console popped up. The application didn't freeze or anything, it's still downloading copying some files. But it completely stopped reacting to any user input - for example clicking the X to close the debug console window does nothing, I can't alt-tab to the installer etc.

**Comment by drojf** [comment]
hmm...i'm pretty lost on this one, I never managed to get that to happen. Does it happen every time or only once?

**Comment by enumag** [comment]
Can't reproduce it again. Closing.
